config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from quotas.printers.views import IndexView

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'),
    # name='home'),
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'),
        name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    # url(r'^users/', include('quotas.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here

    url(r'^printers/', include('quotas.printers.urls', namespace='printers')),
    url(r'^customer/', include('quotas.customers.urls', namespace='customers')), # noqa
    url(r'^quotas/', include('quotas.quotation.urls', namespace='quotations')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar # noqa

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

quotas/customers/urls.py
from django.conf.urls import url

from .views import Customer_Create, Customer_List

urlpatterns = [
    url(r'^list/$', Customer_List.as_view(), name='customer-list'),
    url(r'^create/$', Customer_Create.as_view(), name='new_customer'),
]

quotas/printers/urls.py
from django.conf.urls import url

from .views import Printer_Create, Printer_Detail


# Printers related urls goes here


urlpatterns = [
    url(r'^add/', Printer_Create.as_view(), name='printer-add'),
    url(r'^details/(?P<slug>[\w\-]+)/$', Printer_Detail.as_view(),
        name='printer-detail'),
]

quotas/products/urls.py
from django.conf.urls import url

from .views import Product_list

urlpattern = [
    url('^/<slug>/$', Product_list.as_view(), name='product-details'),
]

quotas/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

quotas/customers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
# from django.db.models.signals import post_save

# Create your models here.


class Customer(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField(User, related_name='customer_profile')
    gender = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    gender = models.CharField(max_length=50, choices=gender)
    address = models.CharField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = _("Customer")
        verbose_name_plural = _("Customers")

    def __str__(self):
        return self.name


# creating the related user
# def create_customer_profile(sender, instance, created, **kwargs):
#        if created:
#           Customer.object.create(user=instance)


# post_save.connect(create_customer_profile, sender=User)

quotas/printers/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _

# Create your models here.


class Printer(models.Model):
    name = models.CharField(_('Name'), max_length=50)
    address = models.CharField(_('Address'), max_length=200)
    email = models.EmailField(_('Email'), max_length=75)
    user = models.OneToOneField(User,
                                related_name='printers_profile')
    phone = models.CharField(_('Telephone'), max_length=75, blank=True)
    bio = models.TextField()
    tag_line = models.CharField(max_length=255, null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    google_plus = models.URLField(null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    logo = models.ImageField(upload_to='printers_logos/',
                             null=True,
                             blank=True)
    slug = models.SlugField(max_length=150, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Printer, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Printer"
        verbose_name_plural = "Printers"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('printer-detail', kwargs={'slug': self.slug})


def save_printer_profile(sender, instance, created, **kwargs):
    if created:
        Printer.objects.create(user=instance)


post_save.connect(save_printer_profile, sender=User)

quotas/products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Weight(models.Model):
    """
    This is regard the weight of the material to use
    """
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = "Weight"
        verbose_name_plural = "Weights"

    def __str__(self):
        self.name


class Material(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    peso = models.ForeignKey(Weight, related_name='Gramaje')

    class Meta:
        verbose_name = "Material"
        verbose_name_plural = "Materiales"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    has_pliegos = models.BooleanField(default=True)
    is_digital = models.BooleanField(default=False)
    material = models.ForeignKey(Material, related_name='Material')
    slug = models.SlugField()

    created_on = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, related_name='Added_by')

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:product-details', args=[str(self.slug)])

quotas/quotation/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext as _

from quotas.printers.models import Printer
from quotas.customers.models import Customer

# Create your models here.


class Material(models.Model):
    """
    This list all types material for the quota
    Bond, satinado, opalina, sulfito, polyester
    """
    name = models.CharField(max_length=50)
    description = models.TextField()

    class Meta:
        verbose_name = "material_type"
        verbose_name_plural = "material_types"

    def __str__(self):
        return self.name


class Quota(models.Model):
    # quota itself
    Offset = 'Offset'
    Digital = 'Digital'

    quota_type = (
        (Digital, 'Offset'),
        (Offset, 'Digital'),
    )

    name = models.CharField(max_length=100)
    description = models.TextField()
    quantity = models.IntegerField()

    before_date = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    responses_number = models.IntegerField(default=0)
    created_by = models.ForeignKey(Customer)

    quota_type = models.CharField(max_length=50, choices=quota_type)
    material = models.ForeignKey('Material')

    # ask Pietro if custom values are suitables
    size = models.CharField(max_length=50)
    quiebres = models.IntegerField()
    single_side = models.BooleanField(default=True)

    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("Quota")
        verbose_name_plural = _("Quotas")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('quota-details', kwargs={'pk': self.pk})


class quota_response(models.Model):
    """ Instance  response for a quota submitted by printer """
    quota = models.ForeignKey(Quota)
    offered_by = models.ForeignKey(Printer)
    cost = models.FloatField()
    deliver_time = models.DateTimeField()
    extra_details = models.TextField()
    has_prepayment = models.BooleanField(default=True)
    prepayment_amount = models.DecimalField(max_digits=4, decimal_places=2)

    created_on = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('quota_offer', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = _("quota_response")
        verbose_name_plural = _("quota_responses")

    def __str__(self):
        return self.id

quotas/customers/forms.py
from django import forms

from .models import Customer


class CustomerForm(forms.ModelForm):
    name = forms.CharField(
        error_messages={'required': 'El campo Nombre es obligatorio'})
    email = forms.CharField(
        error_messages={'required': 'El campo Correo electrónico es obligatorio'}) # noqa
    address = forms.CharField(
        error_messages={'required': 'El campo dirección es obligatorio'})
    phone = forms.CharField(
        error_messages={'required': 'El campo teléfono es obligatorio'})

    class Meta:
        model = Customer
        fields = [
            "name",
            "gender",
            "email",
            "address",
            "phone",
        ]

quotas/printers/forms.py
from django import forms


from .models import Printer


class Printercreation_form(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.email = kwargs.pop('email')
        super(Printercreation_form, self).__init__(*args, **kwargs)

    class Meta:
        model = Printer
        fields = (
            'name',
            'address',
            'email',
            'phone',
            'bio',
            'tag_line',
            'facebook',
            'twitter',
            'google_plus',
            'linkedin',
        )
        exclude = (
            'user',
            'logo',
            'slug',
        )

quotas/products/forms.py
from django import forms

from .models import Product, Material


class ProductCreate_Form(forms.ModelForm):

    class Meta:
        model = Product
        fields = (
            'name',
            'description',
            'has_pliegos',
            'is_digital',
            'material',
        )
        exclude = (
            'added_by',
            'creted_on',
            'slug',

        )


class MaterialCreate_Form(forms.ModelForm):

    class Meta:
        model = Material
        fields = (
            'name',
            'description',
        )

quotas/quotation/forms.py
from django import forms

from .models import Quota


class Quota_Form(forms.ModelForm):

    class Meta:
        model = Quota
        fields = (
            'name',
            'description',
            'quota_type',
            'material',
            'quantity',
            'before_date',
            'size',
            'quiebres',
            'single_side',
        )

quotas/customers/views.py
# from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.edit import CreateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Customer
from .forms import CustomerForm

# Create your views here.


class Customer_Create(LoginRequiredMixin, CreateView):
    model = Customer
    template_name = "customers/create_customer.html"
    form_class = CustomerForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(Customer_Create, self).form_valid(form)


class Customer_List(ListView):
    model = Customer
    template_name = "customers/customers_list.html"
    context_object_name = 'customers'

quotas/printers/views.py
# from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Printer
from .forms import Printercreation_form

# Create your views here.


class IndexView(TemplateView):
    template_name = "index.html"
    model = Printer
    context_object_name = 'printers'


class Printer_Create(LoginRequiredMixin, CreateView):
    model = Printer
    form_class = Printercreation_form
    template_name = "printers/printer_create.html"

    def get_form_kwargs(self):
        kwargs = super(Printer_Create, self).get_form_kwargs()
        kwargs['email'] = self.request.user.email
        return kwargs

    def form_valid(self, form):
        self.form.user = self.request.user
        return super(Printer_Create, self).form_valid(form)


class Printer_Detail(DetailView):
    model = Printer
    template_name = "printers/detail_printer.html"


class PrintersList(ListView):
    """Just to see all printers"""
    model = Printer
    context_object_name = 'printer'

    def __init__(self, arg):
        super(PrintersList, self).__init__()
        self.arg = arg

quotas/products/views.py
# from django.shortcuts import render

from django.views.generic import ListView, DetailView
# from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Product
# Create your views here.


class Product_list(ListView):
    model = Product
    template_name = "product/product_list.html"
    context_object_name = 'products'


class Product_detail(DetailView):
    model = Product
    template_name = "product/product_detail.html"

quotas/quotation/views.py
# from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Quota
from .forms import Quota_Form

# Create your views here.


class Quotas_active_List(ListView):
    model = Quota
    template_name = "quotation/"
    contex_object_name = 'active_quotas'

    def get_queryset(self):
        queryset = super(Quotas_active_List, self).get_queryset()
        return queryset.filter(is_active=True)


class Quota_details(DetailView):
    model = Quota
    template_name = "quotation/quota_details.html"
    contex_object_name = 'quota'


class Quota_Create(LoginRequiredMixin, CreateView):
    model = Quota
    form_class = Quota_Form
    template_name = "quotation/create.html"

    def form_valid(self, form):
        self.object = form.instance
        self.object.created_by = self.user
        return super(Quota_Create, self).form_valid(form)

quotas/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

quotas/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

quotas/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}quotas{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">quotas</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                {% comment %}
                  <!-- <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a> -->
                {% endcomment %}

                  {{ request.user.first_name }}
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

quotas/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Quotas app!</h1>
    <h1>Printers subscribed</h1>

    {% if printers %}
        <ul>
            {% for printer in printers %}
                <li>
                    <a title="{{ printer.name }}" href="{{ printer.get_absolute_url }}">{{ printer.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h4>No printer registered yet!</h4>
        <p>Register your printer <a href="{% url 'printers:printer-add' %}">here</a>.</p>
    {% endif %}

    <h1>Customer space</h1>
    <p>Envie su primera cotizacion: <a href="{% url 'customers:new_customer' %}">Here</a></p>

    <p>Check who has already registered to submit quotas <a href="{% url 'customers:customer-list' %}">here</a>.</p>
{% endblock content %}